{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pickle\n",
    "import cv2\n",
    "from os import listdir\n",
    "from sklearn.preprocessing import LabelBinarizer\n",
    "from keras.models import Sequential\n",
    "from keras.layers.normalization import BatchNormalization\n",
    "from keras.layers.convolutional import Conv2D\n",
    "from keras.layers.convolutional import MaxPooling2D \n",
    "from keras.layers.core import Activation, Flatten, Dropout, Dense\n",
    "from keras import backend as K\n",
    "from keras.preprocessing.image import ImageDataGenerator\n",
    "from keras.optimizers import Adam\n",
    "from keras.preprocessing import image\n",
    "from keras.preprocessing.image import img_to_array\n",
    "from sklearn.preprocessing import MultiLabelBinarizer\n",
    "from sklearn.model_selection import train_test_split\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['Labelled']"
      ]
     },
     "execution_count": 51,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import os\n",
    "os.listdir(\"D:/rdataset/labelledrice\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "EPOCHS = 50\n",
    "BS = 32\n",
    "default_image_size = tuple((224,224))\n",
    "\n",
    "directory_root = 'D:/dataset/labelledrice'\n",
    "image_size = 224\n",
    "width=224\n",
    "height=224\n",
    "depth=3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] Loading images ...\n",
      "[INFO] Processing BrownSpot ...\n",
      "[INFO] Processing Healthy ...\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 23469627 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 17337648 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 16328667 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 16356675 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 16737132 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 13932075 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 15160512 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 11820675 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 17569200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 13495923 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 19691532 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10864227 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 15554187 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9720000 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9687627 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 17583723 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10024752 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7394700 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 14126700 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7641648 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7096332 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7980483 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 13154508 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 6606768 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9655308 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 8710848 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9177003 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12036027 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 15363507 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 8895852 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 11892243 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 15554187 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7179627 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 21482928 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 17758467 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9103692 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10659675 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 18900300 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 11116875 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12607500 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 18125292 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10535628 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12120300 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10278603 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9991875 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 14401443 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 13508652 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7970700 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9904467 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 8608908 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 8895852 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 14731968 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9261147 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 8906187 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9051507 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 16822272 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 11036172 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 11024667 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 13932075 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 13867500 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 6777027 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9515883 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 14718675 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 18436323 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 16793868 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12991683 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 18228675 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12546075 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10750347 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12144432 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12929328 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12301875 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10603200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9601563 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7385283 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 6177675 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10693632 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 6795075 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10535628 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10345347 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10123707 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 11255907 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 8548032 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 8978700 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 11209467 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7489200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 11209467 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10356492 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 18660108 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 8989083 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12929328 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7970700 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 11139987 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7795632 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7096332 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10278603 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7413552 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9335088 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12084147 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 11880300 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10289712 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 17904747 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 14533203 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 18302700 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 17787675 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 9124608 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12411468 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 13610700 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 17685552 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12024012 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 14985675 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 22407867 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7990272 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 8885523 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12036027 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7385283 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7912128 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 7990272 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 15704832 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 15404268 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 12024012 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 17164992 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 11952048 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 19461627 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 22473507 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 13610700 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 22162572 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 14533203 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 5132592 bytes in function 'cv::OutOfMemoryError'\n",
      "\n",
      "Error : OpenCV(4.2.0) C:\\projects\\opencv-python\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 29203200 bytes in function 'cv::OutOfMemoryError'\n",
      "\n"
     ]
    }
   ],
   "source": [
    "def convert_image_to_array(image_dir):\n",
    "    try:\n",
    "        image = cv2.imread(image_dir)\n",
    "        if image is not None :\n",
    "            image = cv2.resize(image, default_image_size)   \n",
    "            return img_to_array(image)\n",
    "        else :\n",
    "            return np.array([])\n",
    "    except Exception as e:\n",
    "        print(f\"Error : {e}\")\n",
    "        return None\n",
    "image_list, label_list = [], []\n",
    "try:\n",
    "    print(\"[INFO] Loading images ...\")\n",
    "    root_dir = listdir(directory_root)\n",
    "    for directory in root_dir :\n",
    "        # remove .DS_Store from list\n",
    "        if directory == \".DS_Store\" :\n",
    "            root_dir.remove(directory)\n",
    "\n",
    "    for plant_folder in root_dir :\n",
    "        plant_disease_folder_list = listdir(f\"{directory_root}/{plant_folder}\")\n",
    "        \n",
    "        for disease_folder in plant_disease_folder_list :\n",
    "            # remove .DS_Store from list\n",
    "            if disease_folder == \".DS_Store\" :\n",
    "                plant_disease_folder_list.remove(disease_folder)\n",
    "\n",
    "        for plant_disease_folder in plant_disease_folder_list:\n",
    "            print(f\"[INFO] Processing {plant_disease_folder} ...\")\n",
    "            plant_disease_image_list = listdir(f\"{directory_root}/{plant_folder}/{plant_disease_folder}/\")\n",
    "                \n",
    "            for single_plant_disease_image in plant_disease_image_list :\n",
    "                if single_plant_disease_image == \".DS_Store\" :\n",
    "                    plant_disease_image_list.remove(single_plant_disease_image)\n",
    "\n",
    "            for image in plant_disease_image_list:\n",
    "                image_directory = f\"{directory_root}/{plant_folder}/{plant_disease_folder}/{image}\"\n",
    "                if image_directory.endswith(\".jpg\") == True or image_directory.endswith(\".JPG\") == True:\n",
    "                    image_list.append(convert_image_to_array(image_directory))\n",
    "                    label_list.append(plant_disease_folder)\n",
    "    print(\"[INFO] Image loading completed\")  \n",
    "except Exception as e:\n",
    "    print(f\"Error --- : {e}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "12552\n"
     ]
    }
   ],
   "source": [
    "image_size = len(image_list)\n",
    "print(image_size)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['BrownSpot' 'Healthy' 'Hispa' 'LeafBlast']\n"
     ]
    }
   ],
   "source": [
    "label_binarizer = LabelBinarizer()\n",
    "image_labels = label_binarizer.fit_transform(label_list)\n",
    "pickle.dump(label_binarizer,open('label_transform.pkl', 'wb'))\n",
    "n_classes = len(label_binarizer.classes_)\n",
    "print(label_binarizer.classes_)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [],
   "source": [
    "from keras.applications import VGG19\n",
    "\n",
    "conv_base = VGG19(weights='imagenet',\n",
    "                  include_top=False,\n",
    "                  input_shape=(224, 224, 3))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "input_2 (InputLayer)         (None, 224, 224, 3)       0         \n",
      "_________________________________________________________________\n",
      "block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      \n",
      "_________________________________________________________________\n",
      "block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     \n",
      "_________________________________________________________________\n",
      "block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         \n",
      "_________________________________________________________________\n",
      "block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     \n",
      "_________________________________________________________________\n",
      "block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    \n",
      "_________________________________________________________________\n",
      "block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         \n",
      "_________________________________________________________________\n",
      "block3_conv1 (Conv2D)        (None, 56, 56, 256)       295168    \n",
      "_________________________________________________________________\n",
      "block3_conv2 (Conv2D)        (None, 56, 56, 256)       590080    \n",
      "_________________________________________________________________\n",
      "block3_conv3 (Conv2D)        (None, 56, 56, 256)       590080    \n",
      "_________________________________________________________________\n",
      "block3_conv4 (Conv2D)        (None, 56, 56, 256)       590080    \n",
      "_________________________________________________________________\n",
      "block3_pool (MaxPooling2D)   (None, 28, 28, 256)       0         \n",
      "_________________________________________________________________\n",
      "block4_conv1 (Conv2D)        (None, 28, 28, 512)       1180160   \n",
      "_________________________________________________________________\n",
      "block4_conv2 (Conv2D)        (None, 28, 28, 512)       2359808   \n",
      "_________________________________________________________________\n",
      "block4_conv3 (Conv2D)        (None, 28, 28, 512)       2359808   \n",
      "_________________________________________________________________\n",
      "block4_conv4 (Conv2D)        (None, 28, 28, 512)       2359808   \n",
      "_________________________________________________________________\n",
      "block4_pool (MaxPooling2D)   (None, 14, 14, 512)       0         \n",
      "_________________________________________________________________\n",
      "block5_conv1 (Conv2D)        (None, 14, 14, 512)       2359808   \n",
      "_________________________________________________________________\n",
      "block5_conv2 (Conv2D)        (None, 14, 14, 512)       2359808   \n",
      "_________________________________________________________________\n",
      "block5_conv3 (Conv2D)        (None, 14, 14, 512)       2359808   \n",
      "_________________________________________________________________\n",
      "block5_conv4 (Conv2D)        (None, 14, 14, 512)       2359808   \n",
      "_________________________________________________________________\n",
      "block5_pool (MaxPooling2D)   (None, 7, 7, 512)         0         \n",
      "=================================================================\n",
      "Total params: 20,024,384\n",
      "Trainable params: 20,024,384\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "conv_base.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 10032 images belonging to 4 classes.\n",
      "Found 2520 images belonging to 4 classes.\n"
     ]
    }
   ],
   "source": [
    "from keras.preprocessing.image import ImageDataGenerator\n",
    "\n",
    "\n",
    "train_dir ='D:/dataset/RiceDiseaseDataset/train'\n",
    "validation_dir ='D:/dataset/RiceDiseaseDataset/validation'\n",
    "test_dir ='D:/dataset/RiceDiseaseDataset/test'\n",
    "\n",
    "# All images will be rescaled by 1./255\n",
    "train_datagen = ImageDataGenerator(rescale=1./255)\n",
    "validation_datagen= ImageDataGenerator(rescale=1./255) \n",
    "\n",
    "train_generator = train_datagen.flow_from_directory(\n",
    "        # This is the target directory\n",
    "        train_dir,\n",
    "        # All images will be resized to 150x150\n",
    "        target_size=(224, 224),\n",
    "        batch_size=20,\n",
    "        # Since we use binary_crossentropy loss, we need binary labels\n",
    "        class_mode='categorical')\n",
    "\n",
    "validation_generator = validation_datagen.flow_from_directory(\n",
    "        validation_dir,\n",
    "        target_size=(224, 224),\n",
    "        batch_size=20,\n",
    "        class_mode='categorical')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 10032 images belonging to 4 classes.\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "could not broadcast input array from shape (20,4) into shape (20)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-41-71ba49cec1ae>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     31\u001b[0m     \u001b[1;32mreturn\u001b[0m \u001b[0mfeatures\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mlabels\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     32\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 33\u001b[1;33m \u001b[0mtrain_features\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtrain_labels\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mextract_features\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtrain_dir\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m10032\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     34\u001b[0m \u001b[0mvalidation_features\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mvalidation_labels\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mextract_features\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mvalidation_dir\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m2520\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     35\u001b[0m \u001b[0mtest_features\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtest_labels\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mextract_features\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtest_dir\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;36m2520\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m<ipython-input-41-71ba49cec1ae>\u001b[0m in \u001b[0;36mextract_features\u001b[1;34m(directory, sample_count)\u001b[0m\n\u001b[0;32m     23\u001b[0m         \u001b[0mfeatures_batch\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mconv_base\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpredict\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minputs_batch\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     24\u001b[0m         \u001b[0mfeatures\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mi\u001b[0m \u001b[1;33m*\u001b[0m \u001b[0mbatch_size\u001b[0m \u001b[1;33m:\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mi\u001b[0m \u001b[1;33m+\u001b[0m \u001b[1;36m1\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m*\u001b[0m \u001b[0mbatch_size\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfeatures_batch\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 25\u001b[1;33m         \u001b[0mlabels\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mi\u001b[0m \u001b[1;33m*\u001b[0m \u001b[0mbatch_size\u001b[0m \u001b[1;33m:\u001b[0m \u001b[1;33m(\u001b[0m\u001b[0mi\u001b[0m \u001b[1;33m+\u001b[0m \u001b[1;36m1\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m*\u001b[0m \u001b[0mbatch_size\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mlabels_batch\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     26\u001b[0m         \u001b[0mi\u001b[0m \u001b[1;33m+=\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     27\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mi\u001b[0m \u001b[1;33m*\u001b[0m \u001b[0mbatch_size\u001b[0m \u001b[1;33m>=\u001b[0m \u001b[0msample_count\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mValueError\u001b[0m: could not broadcast input array from shape (20,4) into shape (20)"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import numpy as np\n",
    "from keras.preprocessing.image import ImageDataGenerator\n",
    "\n",
    "\n",
    "train_dir ='D:/dataset/RiceDiseaseDataset/train'\n",
    "validation_dir ='D:/dataset/RiceDiseaseDataset/validation'\n",
    "test_dir ='D:/dataset/RiceDiseaseDataset/test'\n",
    "\n",
    "datagen = ImageDataGenerator(rescale=1./255)\n",
    "batch_size = 20\n",
    "\n",
    "def extract_features(directory, sample_count):\n",
    "    features = np.zeros(shape=(sample_count, 7, 7, 512))\n",
    "    labels = np.zeros(shape=(sample_count))\n",
    "    generator = datagen.flow_from_directory(\n",
    "        directory,\n",
    "        target_size=(224,224),\n",
    "        batch_size=batch_size,\n",
    "        class_mode='categorical')\n",
    "    i = 0\n",
    "    for inputs_batch, labels_batch in generator:\n",
    "        features_batch = conv_base.predict(inputs_batch)\n",
    "        features[i * batch_size : (i + 1) * batch_size] = features_batch\n",
    "        labels[i * batch_size : (i + 1) * batch_size] = labels_batch\n",
    "        i +=1\n",
    "        if i * batch_size >= sample_count:\n",
    "            # Note that since generators yield data indefinitely in a loop,\n",
    "            # we must `break` after every image has been seen once.\n",
    "            break\n",
    "    return features, labels\n",
    "\n",
    "train_features, train_labels = extract_features(train_dir, 10032)\n",
    "validation_features, validation_labels = extract_features(validation_dir, 2520)\n",
    "test_features, test_labels = extract_features(test_dir, 2520)\n",
    "\n",
    "train_features = np.reshape(train_features, (10032, 7* 7* 512))\n",
    "validation_features = np.reshape(validation_features, (2520, 7* 7* 512))\n",
    "test_features = np.reshape(test_features, (2520, 7* 7* 512))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 64,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "conv2d_9 (Conv2D)            (None, 148, 148, 32)      896       \n",
      "_________________________________________________________________\n",
      "max_pooling2d_9 (MaxPooling2 (None, 74, 74, 32)        0         \n",
      "_________________________________________________________________\n",
      "conv2d_10 (Conv2D)           (None, 72, 72, 64)        18496     \n",
      "_________________________________________________________________\n",
      "max_pooling2d_10 (MaxPooling (None, 36, 36, 64)        0         \n",
      "_________________________________________________________________\n",
      "conv2d_11 (Conv2D)           (None, 34, 34, 128)       73856     \n",
      "_________________________________________________________________\n",
      "max_pooling2d_11 (MaxPooling (None, 17, 17, 128)       0         \n",
      "_________________________________________________________________\n",
      "conv2d_12 (Conv2D)           (None, 15, 15, 128)       147584    \n",
      "_________________________________________________________________\n",
      "max_pooling2d_12 (MaxPooling (None, 7, 7, 128)         0         \n",
      "_________________________________________________________________\n",
      "flatten_6 (Flatten)          (None, 6272)              0         \n",
      "_________________________________________________________________\n",
      "dropout_10 (Dropout)         (None, 6272)              0         \n",
      "_________________________________________________________________\n",
      "dense_19 (Dense)             (None, 512)               3211776   \n",
      "_________________________________________________________________\n",
      "dense_20 (Dense)             (None, 4)                 2052      \n",
      "=================================================================\n",
      "Total params: 3,454,660\n",
      "Trainable params: 3,454,660\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "from keras import layers\n",
    "from keras import models\n",
    "\n",
    "model = models.Sequential()\n",
    "model.add(layers.Conv2D(32, (3, 3), activation='relu',\n",
    "                        input_shape=(150, 150, 3)))\n",
    "model.add(layers.MaxPooling2D((2, 2)))\n",
    "model.add(layers.Conv2D(64, (3, 3), activation='relu'))\n",
    "model.add(layers.MaxPooling2D((2, 2)))\n",
    "model.add(layers.Conv2D(128, (3, 3), activation='relu'))\n",
    "model.add(layers.MaxPooling2D((2, 2)))\n",
    "model.add(layers.Conv2D(128, (3, 3), activation='relu'))\n",
    "model.add(layers.MaxPooling2D((2, 2)))\n",
    "model.add(layers.Flatten())\n",
    "model.add(layers.Dropout(0.5))\n",
    "model.add(layers.Dense(512, activation='relu'))\n",
    "model.add(layers.Dense(4, activation='softmax'))\n",
    "\n",
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "dense_21 (Dense)             (None, 256)               2097408   \n",
      "_________________________________________________________________\n",
      "dropout_11 (Dropout)         (None, 256)               0         \n",
      "_________________________________________________________________\n",
      "dense_22 (Dense)             (None, 4)                 1028      \n",
      "=================================================================\n",
      "Total params: 2,098,436\n",
      "Trainable params: 2,098,436\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "from keras import models\n",
    "from keras import layers\n",
    "from keras.layers import GlobalAveragePooling2D\n",
    "\n",
    "from keras import optimizers\n",
    "\n",
    "model = models.Sequential()\n",
    "model.add(layers.Dense(256, activation='relu', input_dim=4 * 4 * 512))\n",
    "model.add(layers.Dropout(0.5))\n",
    "model.add(layers.Dense(4, activation='softmax'))\n",
    "model.summary()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [
    {
     "ename": "ValueError",
     "evalue": "Error when checking target: expected dense_22 to have shape (4,) but got array with shape (1,)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-66-17137a33e4b1>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      6\u001b[0m                     \u001b[0mepochs\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m30\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      7\u001b[0m                     \u001b[0mbatch_size\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m20\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 8\u001b[1;33m                     validation_data=(validation_features, validation_labels))\n\u001b[0m",
      "\u001b[1;32mD:\\Users\\Habiba Hashmi\\lib\\site-packages\\keras\\engine\\training.py\u001b[0m in \u001b[0;36mfit\u001b[1;34m(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)\u001b[0m\n\u001b[0;32m    950\u001b[0m             \u001b[0msample_weight\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0msample_weight\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    951\u001b[0m             \u001b[0mclass_weight\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mclass_weight\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 952\u001b[1;33m             batch_size=batch_size)\n\u001b[0m\u001b[0;32m    953\u001b[0m         \u001b[1;31m# Prepare validation data.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    954\u001b[0m         \u001b[0mdo_validation\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mFalse\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Users\\Habiba Hashmi\\lib\\site-packages\\keras\\engine\\training.py\u001b[0m in \u001b[0;36m_standardize_user_data\u001b[1;34m(self, x, y, sample_weight, class_weight, check_array_lengths, batch_size)\u001b[0m\n\u001b[0;32m    787\u001b[0m                 \u001b[0mfeed_output_shapes\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    788\u001b[0m                 \u001b[0mcheck_batch_axis\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mFalse\u001b[0m\u001b[1;33m,\u001b[0m  \u001b[1;31m# Don't enforce the batch size.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 789\u001b[1;33m                 exception_prefix='target')\n\u001b[0m\u001b[0;32m    790\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    791\u001b[0m             \u001b[1;31m# Generate sample-wise weight values given the `sample_weight` and\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mD:\\Users\\Habiba Hashmi\\lib\\site-packages\\keras\\engine\\training_utils.py\u001b[0m in \u001b[0;36mstandardize_input_data\u001b[1;34m(data, names, shapes, check_batch_axis, exception_prefix)\u001b[0m\n\u001b[0;32m    136\u001b[0m                             \u001b[1;34m': expected '\u001b[0m \u001b[1;33m+\u001b[0m \u001b[0mnames\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mi\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m+\u001b[0m \u001b[1;34m' to have shape '\u001b[0m \u001b[1;33m+\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    137\u001b[0m                             \u001b[0mstr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mshape\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m+\u001b[0m \u001b[1;34m' but got array with shape '\u001b[0m \u001b[1;33m+\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 138\u001b[1;33m                             str(data_shape))\n\u001b[0m\u001b[0;32m    139\u001b[0m     \u001b[1;32mreturn\u001b[0m \u001b[0mdata\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    140\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mValueError\u001b[0m: Error when checking target: expected dense_22 to have shape (4,) but got array with shape (1,)"
     ]
    }
   ],
   "source": [
    "\n",
    "model.compile(optimizer=optimizers.RMSprop(lr=2e-5),\n",
    "              loss='categorical_crossentropy',\n",
    "              metrics=['acc'])\n",
    "\n",
    "history = model.fit(train_features, train_labels,\n",
    "                    epochs=30,\n",
    "                    batch_size=20,\n",
    "                    validation_data=(validation_features, validation_labels))"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
